package ml.dent.trab;

enum TokenType {
	// Single-character tokens.
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, LEFT_BRACE, RIGHT_BRACE, COLON, PERCENT, NEWLINE, QUESTION, BACKSLASH,QUOTE,DOLLAR,

	// One or two character tokens.
	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,PLUS_EQUAL,MINUS_EQUAL,STAR_EQUAL,SLASH_EQUAL,PERCENT_EQUAL,STAR_STAR_EQUAL, PLUS_PLUS,MINUS_MINUS,ARROW,STAR_STAR,
	// Literals.
	IDENTIFIER, NUMBER,STRING_PART,

	// Keywords.
	AND, XOR, OR, CLASS, ELSE, FALSE, FN, FOR, IF, NULL, RETURN, SUPER, THIS, TRUE, VAR, WHILE,

	EOF
}